on: [push, pull_request, release]

name: Build

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                target:
                    - i686-pc-windows-gnu
                    - i686-unknown-linux-gnu
                    - x86_64-apple-darwin
                    - x86_64-pc-windows-gnu
                    - x86_64-unknown-linux-gnu
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: ${{ matrix.target }}
                  override: true
            - name: Install libssl-dev & pkg-config
              run: sudo apt-get install pkg-config libssl-dev
            - name: Install Clang
              run: sudo apt install clang
            - uses: actions-rs/cargo@v1
              env:
                TARGET_CC: clang
              with:
                command: build
                args: --release --target=${{ matrix.target }}
