on: [push, pull_request, release]

name: Build

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                target:
                    - i686-pc-windows-gnu
                    - i686-unknown-linux-gnu
                    - x86_64-apple-darwin
                    - x86_64-pc-windows-gnu
                    - x86_64-unknown-linux-gnu
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: ${{ matrix.target }}
                  override: true
            - name: Install x86 Build Dependencies
              if: ${{ matrix.target == i686-pc-windows-gnu || matrix.target == i686-unknown-linux-gnu }}
              run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install libssl-dev:i386 clang
            - name: Install x86_64 Build Dependencies
              if: ${{ matrix.target != i686-pc-windows-gnu && matrix.target != i686-unknown-linux-gnu }}
              run: sudo apt-get update && sudo apt-get install pkg-config libssl-dev clang
            - name: Build x86
              uses: actions-rs/cargo@v1
              if: ${{ matrix.target == i686-pc-windows-gnu || matrix.target == i686-unknown-linux-gnu }}
              env:
                  - TARGET_CC: clang
                  - OPENSSL_LIB_DIR: /usr/lib/i386-linux-gnu
                  - OPENSSL_INCLUDE_DIR: /usr/include/i386-linux-gnu/openssl
              with:
                  use-cross: true
                  command: build
                  args: --release --target=${{ matrix.target }}
            - name: Build x86_64
              uses: actions-rs/cargo@v1
              if: ${{ matrix.target != i686-pc-windows-gnu && matrix.target != i686-unknown-linux-gnu }}
              env:
                - TARGET_CC: clang
              with:
                use-cross: true
                command: build
                args: --release --target=${{ matrix.target }}
