on:
    push:
        branches:
            - stable

name: Create Release

env:
    CARGO_TERM_COLOR: always

jobs:
    changelog:
        outputs:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
        name: Create Changelog
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source code
              uses: actions/checkout@v4
            - name: Create Conventional Changelog
              id: changelog
              uses: TriPSs/conventional-changelog-action@v4
              with:
                  github-token: ${{ secrets.github_token }}
                  version-file: './rustfoil-cli/Cargo.toml'
                  version-path: "package.version"
            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v1
              if: ${{ steps.changelog.outputs.skipped == 'false' }}
              with:
                token: ${{ secrets.github_token }}
                tag_name: ${{ steps.changelog.outputs.tag }}
                name: ${{ steps.changelog.outputs.tag }}
                body: ${{ steps.changelog.outputs.clean_changelog }}

    build_linux:
        name: Linux Build
        runs-on: ubuntu-latest
        needs: changelog
        strategy:
            matrix:
                target:
                    - build_target: i686-unknown-linux-gnu
                      arch: x86
                      lib: gnu
                    - build_target: x86_64-unknown-linux-gnu
                      arch: x64
                      lib: gnu
                    - build_target: x86_64-unknown-linux-musl
                      arch: x64
                      lib: musl
        steps:
            - name: Checkout Source code
              uses: actions/checkout@v4
              with:
                ref: "stable"
            - name: Cache Rust dependencies
              uses: actions/cache@v3
              with:
                path: |
                  ~/.cargo/registry
                  ~/.cargo/git
                  rustfoil-cli/target
                  rustfoil-lib/target
                key: ${{ matrix.target.build_target }}-cargo-${{ hashFiles('**/**/Cargo.lock') }}
            - name: Install Rust Toolchain
              uses: dtolnay/rust-toolchain@master
              with:
                toolchain: stable
                target: ${{ matrix.target.build_target }}
            - name: Install Build-Tools
              run: sudo apt-get install build-essential gcc-multilib zstd musl-tools musl-dev
            - name: Build
              run: cd rustfoil-cli && cargo build --release --target=${{ matrix.target.build_target }}
            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ needs.changelog.outputs.upload_url }}
                  asset_path: rustfoil-cli/target/${{ matrix.target.build_target }}/release/rustfoil-cli
                  asset_name: rustfoil_${{ runner.OS }}_${{ matrix.target.lib }}_${{ matrix.target.arch }}
                  asset_content_type: application/x-elf

    build_windows:
        name: Windows Build
        runs-on: windows-latest
        needs: changelog
        strategy:
            matrix:
                target:
                    - build_target: i686-pc-windows-msvc
                      arch: x86
                    - build_target: x86_64-pc-windows-msvc
                      arch: x64
        steps:
            - name: Checkout Source code
              uses: actions/checkout@4
              with:
                  ref: "stable"
            - name: Cache Rust dependencies
              uses: actions/cache@v3
              with:
                path: |
                  ~/.cargo/registry
                  ~/.cargo/git
                  rustfoil-cli/target
                  rustfoil-lib/target
                key: ${{ matrix.target.build_target }}-cargo-${{ hashFiles('**/**/Cargo.lock') }}
            - name: Install Rust Toolchain
              uses: dtolnay/rust-toolchain@master
              with:
                toolchain: stable
                target: ${{ matrix.target.build_target }}
            - name: Build
              run: cd rustfoil-cli && cargo build --release --target=${{ matrix.target.build_target }}
            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ needs.changelog.outputs.upload_url }}
                  asset_path: rustfoil-cli/target/${{ matrix.target.build_target }}/release/rustfoil-cli.exe
                  asset_name: rustfoil_${{ runner.OS }}_${{ matrix.target.arch }}.exe
                  asset_content_type: application/x-msdownload

    build_macos:
      name: MacOS Build
      runs-on: macos-latest
      needs: changelog
      strategy:
        matrix:
          target:
            - build_target: x86_64-apple-darwin
              arch: x64
            - build_target: aarch64-apple-darwin
              arch: aarch64
      steps:
        - name: Checkout Source code
          uses: actions/checkout@v4
          with:
            ref: "stable"
        - name: Cache Rust dependencies
          uses: actions/cache@v3
          with:
            path: |
              ~/.cargo/registry
              ~/.cargo/git
              rustfoil-cli/target
              rustfoil-lib/target
            key: ${{ matrix.target.build_target }}-cargo-${{ hashFiles('**/**/Cargo.lock') }}
        - name: Install Rust Toolchain
          uses: dtolnay/rust-toolchain@master
          with:
            toolchain: stable
            target: ${{ matrix.target.build_target }}
        - name: Build
          run: cd rustfoil-cli && cargo build --release --target=${{ matrix.target.build_target }}
        - name: Upload Release Asset
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ needs.changelog.outputs.upload_url }}
            asset_path: rustfoil-cli/target/${{ matrix.target.build_target }}/release/rustfoil-cli
            asset_name: rustfoil_${{ runner.OS }}_${{ matrix.target.arch }}
            asset_content_type: application/x-elf